### PR TITLE
Remove Aidan from CodeOwner

### PR DESCRIPTION
**Pull request by aidan-kwon**
## Proposed changes

- Remove Aidan from the CodeOwnerlist because I cannot use much of my time for development now. 
- Please add me as a review when my review is needed

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [x] Others

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/kaiachain/kaia/blob/main/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://gist.github.com/kaiachain-dev/bbf65cc330275c057463c4c94ce787a6) and signed by comment `I have read the CLA Document and I hereby sign the CLA` in first time contribute
- [ ] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by aidan-kwon** [comment]
recheck

**Comment by aidan-kwon** [comment]
recheck

**Comment by aidan-kwon** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by aidan-kwon** [comment]
recheck

**Review by ian0371 — APPROVED** [review]

**Review by blukat29 — APPROVED** [review]

**Pull request merged**
