### PR TITLE
docs: Fix word

### PR DESCRIPTION
**Pull request by junha-ahn**
## Proposed changes

Fix word

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [x] Others

## Checklist

- [x] I have read the [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/kaiachain/kaia/blob/main/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://gist.github.com/kaiachain-dev/bbf65cc330275c057463c4c94ce787a6) and signed by comment ```I have read the CLA Document and I hereby sign the CLA``` in first time contribute
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by junha-ahn** [comment]
recheck

**Comment by junha-ahn** [comment]
recheck

**Review by junha-ahn — COMMENTED** [review]
recheck

**Review by junha-ahn — COMMENTED** [review]
**recheck**

**Review by junha-ahn — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Comment by junha-ahn** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by hyeonLewis — APPROVED** [review]
Thanks.

**Review by ian0371 — APPROVED** [review]

**Pull request merged**
